GSA/ckanext-geodatagov

- ckanext/geodatagov/templates/snippets/google_analytics_additional.html
As described in https://github.com/GSA/data.gov/issues/598
> Enable anonymizeIp config for google analytics

- ckanext/geodatagov/templates/package/read_base.html
This should help match the mockup in https://github.com/GSA/data.gov/issues/366
> Remove unused dataset page tab navigation

- ckanext/geodatagov/commands.py
- ckanext/geodatagov/plugins.py
http://catalog.data.gov/dataset?q=groups%3A*
Need a python script to export all the topic datasets, give the below information in the export, python script need to be set up to run as a nightly process and generate the csv file with the timestamp of that day (topic_datasets_03272015.csv, topic_datasets_03282015.csv) , these csv files should be accessible using the public url on the catalog.
Capture below fields in CSV:
- Dataset Title
- Dataset URL
- Organization Name
- Organization Link
- Harvest Source Name
- Harvest Source Link
- Topic Name
- Topic Categories
One dataset could have multiple Topics associated, for each topic repeat a new row. If any of the field contains a comma in the value, have them quoted properly to show them in CSV file. 
As the data grows bigger we can think …
> Export all to csv

- ckanext/geodatagov/plugins.py
I updated the RESOURCE_MAPPING section to include more file types. I also grouped them but file type.
[RESOURCE_MAPPING.txt](https://github.com/GSA/ckanext-geodatagov/files/2267696/RESOURCE_MAPPING.txt)
> RESOURCE_MAPPING Update

- ckanext/geodatagov/commands.py
This fixes the sitemap generation for catalog. Also includes updates to logging for better debugging.
Fixes https://github.com/GSA/datagov-deploy/issues/767
> Include /dataset prefix in sitemap urls

- README.md
For [multi-153](https://github.com/GSA/datagov-ckan-multi/issues/153#issuecomment-579916018)
> Notes on testing

- .env
- README.md
- bin/travis-build.bash
- ckan-docker/Dockerfile
- ckanext/geodatagov/tests/mock_csw_source.py
- docker-compose.yml
- docker_test.ini
- tests/export_test.py
docker-ckan based workflow for ckanext-geodatagov local development
https://github.com/GSA/datagov-ckan-multi/issues/207
> docker-ckan based workflow for ckanext-geodatagov local development

- .circleci/config.yml
run local development docker config in circleci
> run local development docker config in circleci

- bin/travis-build.bash
- ckan-docker/Dockerfile
fix errors related to setuptools and shapely
> fix error related to setuptools upgrade

- deployment/etc/ckan/production.ini
Addresses changes and move to resources.data.gov, ticket number #[1071](https://github.com/GSA/datagov-deploy/issues/1071)
> omb_bureau_codes redirect

- ckanext/geodatagov/templates/source/geodatagov_source_form.html
Realted to [catalog#75](https://github.com/GSA/catalog.data.gov/issues/75)
- Fixed validator_profiles field value
- Fixed private_datasets field value
- fixed css class for this fields
> Fix fields for harvest source form

- ckanext/geodatagov/tests/test_source_form.py
add validator profile field to form test
> add validator profile field to form test

- .env
Just a hotfix after a domain redirect
> Fix Bureau CSV list URL

- bin/travis-build.bash
- ckan-docker/Dockerfile
> Remove patch and start using GSA fork

- ckanext/geodatagov/harvesters/arcgis.py
- ckanext/geodatagov/harvesters/base.py
- ckanext/geodatagov/tests/data-samples/waf1/cb_2016_us_division_500k.shp.iso.xml
- ckanext/geodatagov/tests/data-samples/waf1/index.html
- ckanext/geodatagov/tests/factories.py
- ckanext/geodatagov/tests/mock_static_file_server.py
- ckanext/geodatagov/tests/test_waf.py
Related to [Multi#392](https://github.com/GSA/datagov-ckan-multi/issues/392)
Dealing with dataset marked as private after harvest a source which is set up for public datasets.
> Dealing with a privacy after harvest error

- ckanext/geodatagov/harvesters/base.py
Truncate keywords at 100 characters since DB field is varchar 100
> Truncate keywords at 100 characters

- ckanext/geodatagov/tests/data-samples/waf-gmi/cb_2014_us_necta_500k.shp.iso.xml
- ckanext/geodatagov/tests/data-samples/waf-gmi/index.html
- ckanext/geodatagov/tests/test_waf_GMI.py
- test.ini
This PR:
- Adds test for [Multi#386](https://github.com/GSA/datagov-ckan-multi/issues/386) issue
> Test GMI profile dataset from WAF source

- ckanext/geodatagov/templates/package/read.html
Related to [Catalog#11](https://github.com/GSA/ckanext-datagovcatalog/issues/11)
This PR:
- Use style [defined in DataGovTheme](https://github.com/GSA/ckanext-datagovtheme/pull/50/commits/254fdc6ba3992dcb8bd65f92a6ebb2da76d38808)
> Fix style for Collection button

- ckanext/geodatagov/templates/source/geodatagov_source_form.html
> Change variable name

- bin/travis-build.bash
- ckanext/geodatagov/commands.py
- ckanext/geodatagov/tests/test_json_export.py
Related to [Deploy#567](https://github.com/GSA/datagov-deploy/issues/567)
Depends on PR #159 
This PR:
- Add a new test case for export JSON data and try to parse it as JSON
- Start saving export data as valid JSON data to pass tests
> JSON export command to export real JSON

- README.md
> merge local test command with test section

- ckanext/geodatagov/commands.py
- ckanext/geodatagov/tests/test_json_export.py
Fix JSONL format while export data. ([based on this comment](https://github.com/GSA/ckanext-geodatagov/pull/160/files#r494515501))
> fix JSONL format and test

- ckanext/geodatagov/plugins.py
Bug causes extras_rollup to fail. This simplifies and comments what this code is accomplishing.
Related to https://github.com/GSA/datagov-deploy/issues/2166
Initial tests on staging are clear, harvest working as expected.
> Simplify extras_rollup logic

- .circleci/config.yml
Related to [Multi#463](https://github.com/GSA/datagov-ckan-multi/issues/463)
> Enable CI docker cache

- .circleci/config.yml
- docker-compose.yml
This PR just update the docker image name
> fix docker image name

- README.md
This PR adds some README notes about next steps for this extension
> Notes about update

- ckanext/geodatagov/commands.py
- ckanext/geodatagov/logic.py
Related to [Multi#523](https://github.com/GSA/datagov-ckan-multi/issues/523)
This PR create a new command to update old datasets to new ones using searchable `spatial` field.
> Create a command to update spatial fields

- ckanext/geodatagov/commands.py
- ckanext/geodatagov/tests/test_update_geo.py
Continue #185 
Add tests for `geodatagov update_dataset_geo_fields` command
> Add test for geo command

- .circleci/config.yml
- bin/travis-build.bash
pip 21 no longer support Python 2
> Pip pip version

- ckanext/geodatagov/commands.py
For https://github.com/GSA/datagov-deploy/issues/3403
Fixed syntax errors and optimize queries
> Harvest object relink

- ckanext/geodatagov/plugins/__init__.py
Related to https://github.com/GSA/datagov-deploy/issues/3630
> remove hard coded facets_dict

- ckanext/geodatagov/plugins/__init__.py
In https://github.com/GSA/ckanext-datagovtheme/blob/main/ckanext/datagovtheme/plugin/__init__.py#L24-L76
> remove facets altogether since they are defined in datagovtheme already

- ckanext/geodatagov/logic.py
- ckanext/geodatagov/tests/test_update_geo.py
for https://github.com/GSA/data.gov/issues/3819
> check numbers in spatial parts

- .github/workflows/deploy.yml
- Makefile
- requirements.txt
- setup.py
- https://github.com/GSA/data.gov/issues/3414
added deploy.yml and modified setup.py with install_requires, setup_requires etc
> New: Deploy to PyPI

- =6.2
- README.md
Related to 
- https://github.com/GSA/data.gov/issues/3414
Courtesy of https://badge.fury.io/for/py/ckanext-geodatagov
> PyPI badge

- MANIFEST.in
- setup.py
Related to
- https://github.com/GSA/catalog.data.gov/pull/493
- https://github.com/GSA/data.gov/issues/3414
> Add Missing Files to PyPI Release

- .github/workflows/test.yml
- .gitignore
- Makefile
- README.md
- requirements-py2.txt
- requirements.txt
- setup.py
> update version of ckantoolkit to mirror req from ckanext-harvest

- .github/pull_request_template.md
- setup.py
related to https://github.com/GSA/data.gov/issues/3648
> after all that, still forgot to bump the version

- ckanext/geodatagov/harvesters/arcgis.py
- setup.py
Related to
- https://github.com/GSA/data.gov/issues/3532
> Fix hard fail errors

- ckanext/geodatagov/cli.py
- setup.py
related to https://github.com/GSA/data.gov/issues/3648
> fix urls in sitemap index

- ckanext/geodatagov/cli.py
- setup.py
What to see what package(s) are out of sync.
> print 10 ids

- ckanext/geodatagov/cli.py
Related to [[Add more information for the stuck harvest job report#4184](https://github.com/GSA/data.gov/issues/4184)]
fixed the calculation for time difference with hours.
> fix the calculation for hours

- setup.py
Related to https://github.com/GSA/ckanext-geodatagov/pull/245
> bumps pypi version

- ckanext/geodatagov/logic.py
- setup.py
Related to
- https://github.com/GSA/data.gov/issues/3549
> Log JSON that can't be parsed

- .github/workflows/test.yml
- ckanext/geodatagov/logic.py
- requirements.txt
Related to
- #255 
- https://github.com/GSA/catalog.data.gov/pull/953
> Change the way we capture word-based locations

- ckanext/geodatagov/cli.py
- ckanext/geodatagov/tests/test_sitemap_creation.py
- setup.py
Related to:
- https://github.com/GSA/data.gov/issues/4442
> Fixes sitemap index index

- ckanext/geodatagov/tests/test_category_tags.py
- docker-entrypoint.d/10-setup-db.sh
- requirements.txt
- test.sh
> use harvest latest release
