GSA/ckanext-geodatagov

ckanext/geodatagov/helpers.py, ckanext/geodatagov/plugins.py, ckanext/geodatagov/templates/package/snippets/resource_item.html
Added simple "Open in ArcGIS" for `esri rest` types. This is to the free and anonymous viewer. Optionally people can sign up for a free account but it's not required.
The free map viewer supports KML, CSV, WMS, etc. through the UI, but I'm checking if the `url=` parameter adds these as layers. 
Relates to https://github.com/GSA/data.gov/issues/602
=> Added initial support for open in ArcGIS

ckanext/geodatagov/helpers.py, ckanext/geodatagov/templates/package/snippets/resource_item.html
The `wms=` `kml=` `georss=` varies based on the mime-type.
=> Added support for WMS, KML and GeoRSS to ArcGIS open with

ckanext/geodatagov/plugins.py
Hi,
This is another place that the default text needs to be changed to reflect "Web Resource". The "convert_resource_format" function in "https://github.com/GSA/ckanext-datagovtheme/blob/master/ckanext/datagovtheme/helpers.py" was already updated.
I also found a difference between two functions that I don't understand and wanted to verify they are correct. In both functions I see that an array is created from "RESOURCE_MAPPING.keys()".
In the "change_resource_details" function in this file the "format" seems to be set to the array value of "[0]" from the "RESOURCE_MAPPING" array and the "name" seems to be set to the array value of "[1]" from the "RESOURCE_MAPPING" array. Below is the function:
def change_resource_details(resource): 
formats = RESOURCE_MAPPING.keys() 
resource_format = …
=> Changed the default text from "Web Page" to "Web Resource"

ckanext/geodatagov/commands.py, ckanext/geodatagov/plugins.py
- Reduce the number of packages to operate at one time
- Avoid query on revision
The revision query is way too heavy. Almost every revision is going to be older
than yesterday, so you end up pulling the entire table into memory to compare
against the package table. May as well not use it at all.
=> Query optimization for clean-deleted

bin/travis-build.bash, ckanext/geodatagov/plugins.py, test.ini
- Fix an error to override `before_search` in context without a `request`.
- Upgrade the CI environment by adding missing extensions
This branch is used to test 263 successfully.
=> Avoid error in no-request contexts during tests

ckanext/geodatagov/templates/source/geodatagov_source_form.html
Related to [Validation Schema not being reflected properly in UI](https://github.com/GSA/datagov-deploy/issues/1974).
Tested manually on staging.
=> UI Reflect source config validation

ckanext/geodatagov/commands.py, ckanext/geodatagov/logic.py, ckanext/geodatagov/plugins.py, ckanext/geodatagov/tests/test_waf.py
Related to [Extras Rollup issue with Catalog](https://github.com/GSA/datagov-deploy/issues/2166).
Fix is in place, tests are broken. Desire is to test normal harvest process, make an update, and validate package does not have nested extras_rollup object (current system can build new extras_rollup object with the old extras_rollup object inside the new one, and continue nesting for every change).
=> Limit extras_rollup field building out of control

.circleci/config.yml, ckan-docker/Dockerfile, ckanext/geodatagov/commands.py, ckanext/geodatagov/search.py, ckanext/geodatagov/tests/test_sitemap_creation.py
Related to [Multi#447](https://github.com/GSA/datagov-ckan-multi/issues/447) and [Multi#278](https://github.com/GSA/datagov-ckan-multi/issues/278)
This PR:
- Move custom search function from CKAN 2.3 fork (278)
- Allow `sitemap-to-s3` command to run without uploading to S3
- Add tests to this XML files creation locally 
- Preserve 2.3 compatibility
=> Allow sitemap generation for CKAN 2.8

ckanext/geodatagov/logic.py, ckanext/geodatagov/tests/test_fix_packages.py, ckanext/geodatagov/tests/test_json_export.py, ckanext/geodatagov/tests/test_sitemap_creation.py
Related to [Multi#472](https://github.com/GSA/datagov-ckan-multi/issues/472)
Before saving a dataset move back `tags` as regular field and no as an `extra`
Require more analysis. This is not a simple change
=> Avoid tags as extras before save a package

ckanext/geodatagov/logic.py, ckanext/geodatagov/tests/test_datajson.py, ckanext/geodatagov/tests/test_fix_spatial.py, docker-compose.yml, test.ini
Related to [Multi#523](https://github.com/GSA/datagov-ckan-multi/issues/523) and [Multi#332](https://github.com/GSA/datagov-ckan-multi/issues/332)
This PR:
- Transform old spatial data in `ckanext-spatial` required format (GeoJSON)
- Add test for old spatial data
- Start using SOLR and DB images including the locations table
=> Start spatial data transformation to fit new specs

ckanext/geodatagov/logic.py
Single PR after discovering error while logging
```
Traceback (most recent call last):
File "/usr/bin/ckan", line 45, in <module>
load_entry_point('PasteScript', 'console_scripts', 'paster')()
File "/usr/lib/ckan/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
invoke(command, command_name, options, args[1:])
File "/usr/lib/ckan/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
exit_code = runner.run(args)
File "/usr/lib/ckan/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
result = self.command()
File "/usr/lib/ckan-new/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 237, in command
utils.fetch_consumer()
File "/usr/lib/ckan-new/src/ckanext-harvest/ckanext/harvest/utils.py", line 351, in fetch_consumer …
```
=> Fix error while loging

ckanext/geodatagov/templates/templates_2_8/source/geodatagov_source_form.html, ckanext/geodatagov/templates/templates_new/source/geodatagov_source_form.html
This fix does pull the correct source info.
The data is being set properly, but this will allow it to display
properly.
Related to https://github.com/GSA/datagov-deploy/issues/897
=> Update for getting source info

requirements.txt, setup.py
Related to
- https://github.com/GSA/data.gov/issues/3414
- https://github.com/GSA/catalog.data.gov/pull/493
Changes:
- `ply` is a ckanext-geodatagov requirement
- `ply` does not need to be pinned.
=> Track Ply as requirement

.github/pull_request_template.md, setup.py
Related to https://github.com/GSA/data.gov/issues/3648
Weird, looks like [0.1.3](https://pypi.org/project/ckanext-geodatagov/0.1.3/) is already out there.
=> apparently 0.1.3 was published in July?

ckanext/geodatagov/cli.py, ckanext/geodatagov/tests/test_db_solr_sync.py
Related to
- https://github.com/GSA/data.gov/issues/3985
- https://github.com/GSA/data.gov/issues/2213
This should be more efficient 🦅 
It takes too long to update `package_id` one by one. Use `rebuild` function, take `package_ids` with defer_commit as True. It should speed things up.
=> DB Solr Sync - Defer commit

ckanext/geodatagov/cli.py, setup.py, test.ini
Related to 
- https://github.com/GSA/data.gov/issues/4007
To speed up the solr index deletion for large set, did following changes:
- Add new function to delete indexes in solr with one connection and commit at the end.
- Pass list of package ids to the new delete function to speed up.
=> Optimize db solr sync to speed up the deletion of large amount solr indexes

README.md, ckanext/geodatagov/cli.py, ckanext/geodatagov/tests/test_tracking.py, setup.py
Related to https://github.com/GSA/data.gov/issues/1479
Copied from core `ckan tracking update` command, but used custom rebuild command to achieve
- better logging,
- faster solr indexing with defer commit,
- ignore index error and continue
TODO: make it resume-able. Without it, It will be difficult to impossible to fix some error due to Solr index glitches when updating large amount of data.
=> add custom command ckan geodatagov tracking-update

ckanext/geodatagov/cli.py, setup.py
Quick fix
Use click.echo not sys.stdout to get rid of linebreaking issue.
=> Click echo

ckanext/geodatagov/harvesters/arcgis.py, setup.cfg, setup.py
Related to 
https://github.com/GSA/data.gov/issues/4065 
https://github.com/GSA/data.gov/issues/4108
Harvest failure from https://gisportal.ibwc.gov/agsportal/
- Added extra '/' for source URL to avoid the path lost.
- Changed the encode for [ ] in the search query.
- Fixed Python3 errors.
=> Fix harvest failure

ckanext/geodatagov/cli.py, setup.py
Related to https://github.com/GSA/data.gov/issues/4061
=> CKAN_SITE_URL urls in sitemap index + refactoring

ckanext/geodatagov/cli.py, dev-requirements.txt, setup.py
[Set up a task to find stuck harvest jobs#4058](https://github.com/GSA/data.gov/issues/4058)
added function to find out the stuck harvest jobs which running more than 1 day.
=> Check stuck harvest jobs

.github/pull_request_template.md
Just fixing the PR template link to point to the main branch instead of whatever weird thing I had put in there before.
=> Update setup.py template link to point to main

MANIFEST.in, requirements.txt, setup.py
Related to https://github.com/GSA/data.gov/issues/4173
iso transformation failed due to missing xslt file
=> update MANIFEST.in add *.xslt

ckanext/geodatagov/cli.py, setup.py
Related to [[Add more information for the stuck harvest job report#4184](https://github.com/GSA/data.gov/issues/4184)]
We have a stuck job reported on production, but job shows finished about 11 hours, so we need to add more information in the check-stuck-job command to capture states at the time reporting stuck jobs.
=> Add info to check stuck job

setup.py
Bumped version number in [setup.py](https://github.com/GSA/ckanext-geodatagov/blob/main/setup.py#L13) (also checked on [PyPi](https://pypi.org/project/ckanext-geodatagov/#history)).
=> change pypi version

ckanext/geodatagov/cli.py, setup.py
Related to [[Add more information for the stuck harvest job report#4184](https://github.com/GSA/data.gov/issues/4184)]
Changed the way to check time difference between now and created time. And output the raw format of the time diff.
=> Fix issue for checking stuck jobs with time difference format 

ckanext/geodatagov/cli.py, setup.py
Related to [[Add more information for the stuck harvest job report#4184](https://github.com/GSA/data.gov/issues/4184)]
Added the missing condition for running job only as old job has same source_id.
=> Fix check stuck jobs issue

ckanext/geodatagov/cli.py, ckanext/geodatagov/tests/test_db_solr_sync.py, setup.py
Related to https://github.com/GSA/data.gov/issues/4177
This add `harvest_object_id` into db-solr-sync, so that we are comparing tuple `(package_id, last_modified_date, harvest_object_id)` between dn and solr to determine if a package need a re-index.
=> Sync harvest object

ckanext/geodatagov/logic.py, ckanext/geodatagov/tests/test_update_geo.py, setup.py, test.sh
Related to https://github.com/GSA/data.gov/issues/3549
=> Spatial plus sign fix

ckanext/geodatagov/logic.py, setup.py
Related to
- #251 
- https://github.com/GSA/catalog.data.gov/pull/890#pullrequestreview-1355455689
Changes:
- New Leading Zero Regex: `(\s)(-?)0+((0|[1-9][0-9]*)(\.[0-9]*)?)`
- Test Conditions
```bash
14.601813, 080, 080.012, 83.0312, 090.01, 
14.01813, 0.001, -1.2, -010.02, -010.02000,
14.332601813, 080, 00334, 01, 02, 03
0.0123, 0.123, 000123
0.001, 0.01, 02, 
```
=> Fix leading zero regex

ckanext/geodatagov/cli.py, setup.py
Bumping sitemap page size count from 1k to 10k to hopefully help Google Search Console along.
=> changed page size to 10k

ckanext/geodatagov/cli.py, setup.py
Looks like we need to turn manual relink process into a nightly job since we see a few thousand packages that need to be relinked in every a few days. This commit change solr indexing from package by package to batch processing, so it speeds up the process to make it ready to turn into a GH cron action.
=> speed up relink by improving solr indexing

ckanext/geodatagov/cli.py, ckanext/geodatagov/tests/test_db_solr_sync.py, setup.py
Related to https://github.com/GSA/data.gov/issues/4355
db-solr-sync script does not know how to handle datasets without harvest objects. We should exclude them from the update list to save the resource
=> skip datasets without harvest object from db-solr-sync

Dockerfile, ckanext/geodatagov/cli.py, ckanext/geodatagov/tests/test_sitemap_creation.py, requirements.txt, setup.py
Related to
- https://github.com/GSA/catalog.data.gov/issues/990
Changes:
- Add more common code to `Sitemap` class
- Extend `Sitemap` class to `SitemapIndex` and `SitemapData` for better abstraction
- Delete each sitemap object + temporary files explicitly after upload
=> Refactor sitemap generation code

ckanext/geodatagov/logic.py, setup.py
old_spatial_transformed could be ""
Error on prod fetch complaining IndexError on line 
`if old_spatial_transformed[-1] == '.':`
=> Spatial empty string

ckanext/geodatagov/search.py, setup.py
Related to https://github.com/GSA/catalog.data.gov/issues/990
=> uses 'fl' instead of 'fields' to only return the fields we care about

setup.py
Related to https://github.com/GSA/ckanext-geodatagov/pull/265
=> bumps pypi version to 0.2.4

ckanext/geodatagov/cli.py, setup.py
Related to https://github.com/GSA/catalog.data.gov/issues/1075
`S3` is from `S3 = boto3.client()`, not `S3 = boto3.resource()`. A better name would be `s3_client`.
=> S3 delete objects

ckanext/geodatagov/cli.py, setup.py
Related to https://github.com/GSA/catalog.data.gov/issues/1075
Use `delete_object` instead of `delete_objects`
=> use s3 delete-object to avoid Content-MD5 error

ckanext/geodatagov/helpers.py, ckanext/geodatagov/templates/package/read.html, setup.py
Related to https://github.com/GSA/data.gov/issues/4553
- added exception for parent dataset absent in collection
- changed the UI to display differently to still allow user to search other datasets within same collection.
=> fix UI issue when a collection dataset with missing parent

Dockerfile, Makefile, README.md, ckanext/geodatagov/cli.py, setup.py, test.sh
catalog-next has no harvest objects. `db-solr-sync-next` is am simplified version of `db-solr-sync`.
=> Add db-solr-sync-next for catalog-next

ckanext/geodatagov/plugin.py, setup.py
Related to https://github.com/GSA/data.gov/issues/5091
This one log is something like 30% of our messages in catalog-web on prod. It is of no value for us to see this as a log message because we don't do anything about it. This moves it to the `DEBUG` level so we won't see it in production.
=> Make a very frequent log message debug

Dockerfile
This minor commit changes ckan base image from outdated `openknowledge` to `ckan`, it will also bump ckan core from 2.10.1 to 2.10.7.
=> update ckan docker image
